### ISSUE TITLE
Add prerequisite info to beginning of course

### ISSUE THREAD

**Issue by wdower** [mitre/inspec-advanced-developer-v1#6]
“For this follow-on advanced class (basic is a preferred prerequisite), we’ll be writing InSpec Resources in the Ruby language, so it is highly recommended students of the advanced class unfamiliar with Ruby review the following Ruby primers:
https://www.ruby-lang.org/en/documentation/quickstart/  
https://www.youtube.com/watch?v=t_ispmWmdjY&vl=en”

**Comment by karikarshivani** [comment]
Committed to master
